### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by jwhendy** [ros-melodic-arch/ros-melodic-moveit-ros-planning-interface#3]
I get pretty unhelpful output from my build attempt. Any suggestions?
```
[ 10%] Built target octomap_msgs_generate_messages_eus
[ 10%] Built target octomap_msgs_generate_messages_cpp
make[1]: *** [CMakeFiles/Makefile2:2465: py_bindings_tools/CMakeFiles/moveit_py_bindings_tools.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:2515: common_planning_interface_objects/CMakeFiles/moveit_common_planning_interface_objects.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by jwhendy** [comment]
Ah, found [this](https://github.com/ros-planning/moveit_ros/issues/302) which led me to suspect the python version. This package is also affected by needing python 3.8 settings.

**Comment by acxz** [comment]
Fixed by latest merge, need to sync.

**Comment by jwhendy** [comment]
Anything holding this back? I had a `btrfs` glitch and had to reinstall, which prompts me to notice this is pretty outdated on AUR.

**Comment by acxz** [comment]
@bionade24 can you take a real quick look at this one as well? EDIT: was synced
